// src/components/game.svelte
<script lang="ts">
  import Board from "./board.svelte";
  let history = $state([Array(9).fill(null)]);
  let currentMove = $state(0);
  let xIsNext = $derived(currentMove % 2 === 0);
  let currentSquares = $derived(history[currentMove]);
  
  function handlePlay(nextSquares: string[]) {
    let nextHistory = $derived([
      ...history.slice(0, currentMove + 1),
      nextSquares,
    ]);
    history = nextHistory;
    currentMove = nextHistory.length - 1;
  }

  function jumpTo(nextMove: number) {
    currentMove = nextMove;
  }
  const moves = $derived.by(() => {
    history.map((_squares: string[], move) => {
      let description = $state();
      if (move > 0) {
        description = `Go to move #${move}`;
      } else {
        description = `Go to game start`;
      }

      return (
        <li>
          <button
            class="p-2 border rounded active:scale-[98%]"
            type="button"
            onclick={() => jumpTo(move)}
          >
            {description}
          </button>
        </li>
      );
    });
  });
</script>

<div class="py-2">
  <Board {xIsNext} squares={currentSquares} onPlay={handlePlay} />
  <ul class="flex flex-col gap-3">{moves}</ul>
</div>

// src/game.tsx
import { useState } from "react";
import Board from "./board";

export default function Game() {
  const [history, SetHistory] = useState([Array(9).fill(null)]);
  const [currentMove, setCurrentMove] = useState(0);
  const xIsNext = currentMove % 2 === 0;
  const currentSquares = history[currentMove];

  const handlePlay = (nextSquares) => {
    const nextHistory = [...history.slice(0, currentMove + 1), nextSquares];

    SetHistory(nextHistory);
    setCurrentMove(nextHistory.length - 1);

    console.log(currentMove);
  };

  const jumpTo = (nextMove: number) => {
    setCurrentMove(nextMove);
  };

  const moves = history.map((squares, move) => {
    let description;
    if (move > 0) {
      description = `Go to move #${move}`;
    } else {
      description = "Go to game start";
    }

    return (
      <li key={move}>
        <button onClick={() => jumpTo(move)}>{description}</button>
      </li>
    );
  });

  return (
    <div>
      <div>
        <Board xIsNext={xIsNext} squares={currentSquares} onPlay={handlePlay} />
      </div>
      <div>
        <ol>{moves}</ol>
      </div>
    </div>
  );
}
